---
overwrite: true
prefer_grub_d: false
keep_distributor: false
kernel_params: [ "quiet", "splash", "console=ttyAMA0,115200" ]
defaults:
  GRUB_TIMEOUT: 5
  GRUB_TIMEOUT_STYLE: "menu"
  GRUB_DEFAULT: "0"
  GRUB_DISABLE_SUBMENU: true
  GRUB_TERMINAL_OUTPUT: "gfxterm"
  GRUB_DISABLE_RECOVERY: true
  GRUB_DISABLE_OS_PROBER: true
