---
dontChroot: false
timeout: 30
verbose: true

script:
  - "-rm -r /etc/mkinitcpio.conf.d/"
  - "rm -f /etc/mkinitcpio.conf.d/archiso.conf"
  - "sed -i 's/^MODULES=(/MODULES=(virtio_gpu virtio_blk virtio_scsi virtio_pci /' /etc/mkinitcpio.conf"
  - "sed -i \"s/PRESETS=('archiso')/PRESETS=('default')/\" /etc/mkinitcpio.d/linux-aarch64.preset"
  - "sed -i 's|archiso_config=.*|default_config=\"/etc/mkinitcpio.conf\"|' /etc/mkinitcpio.d/linux-aarch64.preset"
  - "sed -i 's|archiso_image=|default_image=|' /etc/mkinitcpio.d/linux-aarch64.preset"
  - "sed -i 's|^default_image=.*|default_image=\"/boot/initramfs-linux-aarch64.img\"|' /etc/mkinitcpio.d/linux-aarch64.preset"
  - "/usr/share/churros/scripts/publish-aarch64-kernel --require"
